#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
#Distribute requests using a roundrobin algorithm
#Make sure that HAproxy can be managed via an init script

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 3.84.239.19
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 251885-web-01 100.26.136.254 check
    server 251885-web-02 100.27.2.102 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
