#!/usr/bin/env bash

# Set the input file path
myfile="/etc/passwd"

# Read /etc/passwd line by line and display user information
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7; 
do
	echo "The user ${f1} is part of the ${f4} gang, lives in ${f6} and rides ${f7}."
	echo "${f3}'s place is protected by the passcode ${f2}, more info about the user here: ${f5}"
	echo
done < "$myfile"

