#!/usr/bin/env bash
#  Bash script that displays the content of the file /etc/passwd

myfile="/etc/passwd"
f1=""
f2=""
f3=""
while IFS= read -r line
do
	fi="$(echo "$line" | cut -d":" -f1)"
	fi="$(echo "$line" | cut -d":" -f4)"
	fi="$(echo "$line" | cut -d":" -f6)"
 	fi="$(echo "$line" | cut -d":" -f7)"
	fi="$(echo "$line" | cut -d":" -f3)"
	fi="$(echo "$line" | cut -d":" -f2)"
	fi="$(echo "$line" | cut -d":" -f5)"
	echo "The user ${f1} is part of the ${f2} gang, lives in ${f3} and rides ${f5} place is protected by the passcode ${f6}, more info about the user here: ${f17}"
done < "$myfile"
