#!/usr/bin/env bash
#  Bash script that displays the content of the file /etc/passwd

myfile="/etc/passwd"
f1="$USERNAME"
f2="$GROUP_ID"
f3="$HOME_DIRECTORY"
f4="$COMMAND"
f5="$SHELL"
f6="$USER"
f7="$ID"
f8="$PASSWORD"


while IFS= read -r line
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND/$SHELL"
	echo "$USER $ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER $ID INFO"
	#echo "$line" | cut -d":"

done < "$myfile"
